### Deploy example function
POST http://localhost:5000/deploy/example HTTP/1.1


### Check deployment status (paste id from deploy response)
GET http://localhost:5000/deploy/status/{{deployment_id}} HTTP/1.1


### List tracked replicas in Redis
GET http://localhost:5000/functions/example/replicas HTTP/1.1


### Invoke example #1
POST http://localhost:5000/invoke/example HTTP/1.1
Content-Type: application/json

{
	"name": "test-1"
}


### Invoke example #2
POST http://localhost:5000/invoke/example HTTP/1.1
Content-Type: application/json

{
	"name": "test-2"
}


### Invoke example #3
POST http://localhost:5000/invoke/example HTTP/1.1
Content-Type: application/json

{
	"name": "test-3"
}


### Show all deployed functions
GET http://localhost:5000/functions HTTP/1.1
